#!/usr/bin/env bash
set -euo pipefail

log() { printf "\n\033[1m%s\033[0m\n" "$*"; }

ZSH_DIR="${ZSH:-$HOME/.oh-my-zsh}"
ZSH_CUSTOM_DIR="${ZSH_CUSTOM:-$ZSH_DIR/custom}"
PLUGINS_DIR="$ZSH_CUSTOM_DIR/plugins"

ZSHRC="$HOME/.zshrc"
ZSHRC_BAK="$HOME/.zshrc.bak.$(date +%Y%m%d-%H%M%S)"

ensure_repo() {
  local name="$1"
  local repo="$2"
  local dest="$PLUGINS_DIR/$name"

  if [[ -d "$dest/.git" ]]; then
    log "Plugin already installed: $name (updating)"
    git -C "$dest" pull --ff-only || true
  elif [[ -d "$dest" ]]; then
    log "Plugin directory exists (not a git repo): $name (skipping clone)"
  else
    log "Installing plugin: $name"
    git clone --depth=1 "$repo" "$dest"
  fi
}

log "Zsh config + plugins"

# Basic sanity checks
if [[ ! -d "$ZSH_DIR" ]]; then
  echo "Oh My Zsh not found at: $ZSH_DIR"
  echo "Run scripts/40-ohmyzsh.sh first."
  exit 1
fi

mkdir -p "$PLUGINS_DIR"

# Install external plugins into Oh My Zsh custom plugins dir
# zsh-autosuggestions: inline suggestions based on history
ensure_repo "zsh-autosuggestions" "https://github.com/zsh-users/zsh-autosuggestions.git"

# fast-syntax-highlighting: fast command syntax highlighting
ensure_repo "fast-syntax-highlighting" "https://github.com/zdharma-continuum/fast-syntax-highlighting.git"

# zsh-autocomplete: realtime type-ahead autocompletion
ensure_repo "zsh-autocomplete" "https://github.com/marlonrichert/zsh-autocomplete.git"

# Backup existing .zshrc if it exists
if [[ -f "$ZSHRC" ]]; then
  log "Backing up existing ~/.zshrc to: $ZSHRC_BAK"
  cp "$ZSHRC" "$ZSHRC_BAK"
fi

log "Writing new ~/.zshrc"

cat > "$ZSHRC" <<'EOF'
# ~/.zshrc
# Generated by mac-setup
#
# Oh My Zsh:
#   - Theme: maran (built-in)
#   - Plugins: git, zsh-autosuggestions, fast-syntax-highlighting, zsh-autocomplete

###############################################################################
# Oh My Zsh base
###############################################################################
export ZSH="$HOME/.oh-my-zsh"

# Theme: "maran" (built into oh-my-zsh)
ZSH_THEME="maran"

# Plugins (requested)
# Note: load order matters; these are generally safe together.
plugins=(git zsh-autosuggestions fast-syntax-highlighting zsh-autocomplete)

# Optional: disable automatic updates prompts (set to "auto" or "disabled")
# zstyle ':omz:update' mode disabled

# Faster completion init (can reduce startup time)
# If you see completion weirdness, remove -C.
autoload -Uz compinit
compinit -C

# Load Oh My Zsh
source "$ZSH/oh-my-zsh.sh"

###############################################################################
# History
###############################################################################
HISTFILE="$HOME/.zsh_history"
HISTSIZE=200000
SAVEHIST=200000
setopt INC_APPEND_HISTORY         # append history as you go
setopt SHARE_HISTORY              # share between sessions
setopt HIST_IGNORE_DUPS           # no duplicates
setopt HIST_IGNORE_ALL_DUPS       # remove older duplicates
setopt HIST_REDUCE_BLANKS         # trim blanks
setopt EXTENDED_HISTORY           # timestamps

###############################################################################
# Completion & UX
###############################################################################
setopt AUTO_CD                    # cd by typing directory name
setopt AUTO_PUSHD                 # pushd on cd
setopt PUSHD_IGNORE_DUPS
setopt CORRECT                    # command correction (disable if annoying)

# Make tab completion menu nicer
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

###############################################################################
# Keybindings
###############################################################################
bindkey -e                         # emacs mode (common default)
bindkey '^R' history-incremental-search-backward

###############################################################################
# Useful aliases
###############################################################################
alias ll='ls -lah'
alias la='ls -la'
alias ..='cd ..'
alias ...='cd ../..'
alias grep='grep --color=auto'

# Git shortcuts
alias gs='git status'
alias gl='git log --oneline --decorate -n 20'
alias gp='git pull'
alias gpp='git pull --rebase'
alias gd='git diff'
alias gco='git checkout'
alias gb='git branch'

###############################################################################
# Tool integrations (auto-detect if installed)
###############################################################################

# Homebrew shellenv (ensures brew is available in new shells)
if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -x /usr/local/bin/brew ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi

# fzf integration (if installed by brew)
if [[ -n "$HOMEBREW_PREFIX" && -f "$HOMEBREW_PREFIX/opt/fzf/shell/completion.zsh" ]]; then
  source "$HOMEBREW_PREFIX/opt/fzf/shell/completion.zsh"
fi
if [[ -n "$HOMEBREW_PREFIX" && -f "$HOMEBREW_PREFIX/opt/fzf/shell/key-bindings.zsh" ]]; then
  source "$HOMEBREW_PREFIX/opt/fzf/shell/key-bindings.zsh"
fi

# zoxide (if installed)
if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init zsh)"
fi

# Starship (optional) — disabled because you requested Oh My Zsh theme "maran".
# If you ever switch to Starship, set ZSH_THEME="" and uncomment:
# if command -v starship >/dev/null 2>&1; then
#   eval "$(starship init zsh)"
# fi

###############################################################################
# Local overrides (optional)
###############################################################################
# Put machine-specific stuff here so regen doesn't stomp it:
#   ~/.zshrc.local
if [[ -f "$HOME/.zshrc.local" ]]; then
  source "$HOME/.zshrc.local"
fi
EOF

log "Zsh config complete ✅"
echo "New ~/.zshrc written. Restart your terminal or run:"
echo "  exec zsh -l"